[build]
  publish = "dist"
  command = "npm run build"

# Tidak perlu lagi karena akses langsung
# [[redirects]]
#   from = "/api/*"
#   to = "https://howa-technology.wuaze.com/api/v1/:splat"
#   status = 200
#   force = true